site_name:           DynamicalBilliards.jl
repo_url:            https://github.com/JuliaDynamics/DynamicalBilliards.jl
site_description:    An easy-to-use, modular and extendable Julia package for Dynamical Billiard systems in two dimensions.
site_author:         George Datseris

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'cyan'
  font:
    text: 'Montserrat'
    code: 'Source Code Pro'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/JuliaDynamics/DynamicalBilliards.jl'

markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - mdx_math
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets\Documenter.css


extra_javascript:
  - assets\mathjaxhelper.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

docs_dir: 'build'

pages:
- Introduction: index.md
- High Level API: basic/high_level.md
- Visualizing: visualizing.md
- Phase Spaces: basic/phasespaces.md
- Ray-Splitting: ray-splitting.md
- Lyapunov Exponents: lyapunovs.md
- MushroomTools: mushroomtools.md
- Physics: physics.md
- Internals: basic/low_level.md
- Tutorials:
  - Defining a Billiard: tutorials/billiard_table.md
  - Creating your own Obstacle: tutorials/own_obstacle.md
  - Examples: tutorials/examples.md
